
package com.content.hce;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * 银联HCE接入
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "unionPayHce", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/unionPay_response_unit")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnionPayHce {


    /**
     * 账户验证/激活码申请/云卡激活
     * 
     * @param parameters
     * @return
     *     returns com.content.hce.CheckGlobalEligibilityResponse
     */
    @WebMethod(operationName = "CheckGlobalEligibility")
    @WebResult(name = "CheckGlobalEligibilityResponse", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
    public CheckGlobalEligibilityResponse checkGlobalEligibility(
        @WebParam(name = "CheckGlobalEligibilityRequest", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
        CheckGlobalEligibilityRequest parameters);

    /**
     * 云卡注销
     * 
     * @param parameters
     * @return
     *     returns com.content.hce.TerminateServiceResponse
     */
    @WebMethod(operationName = "TerminateService")
    @WebResult(name = "TerminateServiceResponse", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
    public TerminateServiceResponse terminateService(
        @WebParam(name = "TerminateServiceRequest", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
        TerminateServiceRequest parameters);

    /**
     * 云卡部署通知
     * 
     * @param parameters
     * @return
     *     returns com.content.hce.DeployServiceResponse
     */
    @WebMethod(operationName = "DeployService")
    @WebResult(name = "DeployServiceResponse", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
    public DeployServiceResponse deployService(
        @WebParam(name = "DeployServiceRequest", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
        DeployServiceRequest parameters);

    /**
     * 云卡或主账户的暂停/恢复
     * 
     * @param parameters
     * @return
     *     returns com.content.hce.SuspendOrResumeServiceResponse
     */
    @WebMethod(operationName = "SuspendOrResumeService")
    @WebResult(name = "SuspendOrResumeServiceResponse", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
    public SuspendOrResumeServiceResponse suspendOrResumeService(
        @WebParam(name = "SuspendOrResumeServiceRequest", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
        SuspendOrResumeServiceRequest parameters);

    /**
     * 主帐号和主帐号有效期更换
     * 
     * @param parameters
     * @return
     *     returns com.content.hce.ExchangeServiceDataResponse
     */
    @WebMethod(operationName = "ExchangeServiceData")
    @WebResult(name = "ExchangeServiceDataResponse", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
    public ExchangeServiceDataResponse exchangeServiceData(
        @WebParam(name = "ExchangeServiceDataRequest", targetNamespace = "http://www.artery.org/projects/NBUnionPayHce/UnionPay_hce", partName = "parameters")
        ExchangeServiceDataRequest parameters);

}
