
package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AmBankPortType", targetNamespace = "http://ws.tsm.cup.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AmBankPortType {


    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.MpanApplyResponse
     */
    @WebMethod
    @WebResult(name = "mpanApplyResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public MpanApplyResponse mpanApply(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "mpanApplyRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        MpanApplyRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.MappingNotifyResponse
     */
    @WebMethod
    @WebResult(name = "mappingNotifyResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public MappingNotifyResponse mappingNotify(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "mappingNotifyRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        MappingNotifyRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.TriggerOtpResponse
     */
    @WebMethod
    @WebResult(name = "triggerOtpResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public TriggerOtpResponse triggerOtp(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "triggerOtpRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        TriggerOtpRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.VerifyOtpResponse
     */
    @WebMethod
    @WebResult(name = "verifyOtpResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public VerifyOtpResponse verifyOtp(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "verifyOtpRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        VerifyOtpRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.CupMpanOperationNotifyResponse
     */
    @WebMethod
    @WebResult(name = "cupMpanOperationNotifyResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public CupMpanOperationNotifyResponse cupMpanOperationNotify(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "cupMpanOperationNotifyRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        CupMpanOperationNotifyRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.OperationResultNotifyResponse
     */
    @WebMethod
    @WebResult(name = "operationResultNotifyResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public OperationResultNotifyResponse operationResultNotify(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "operationResultNotifyRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        OperationResultNotifyRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.CupblackListSyncResponse
     */
    @WebMethod
    @WebResult(name = "cupblackListSyncResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public CupblackListSyncResponse cupblackListSync(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "cupblackListSyncRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        CupblackListSyncRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.MpanApplyExceptionNotifyResponse
     */
    @WebMethod
    @WebResult(name = "mpanApplyExceptionNotifyResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public MpanApplyExceptionNotifyResponse mpanApplyExceptionNotify(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "mpanApplyExceptionNotifyRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        MpanApplyExceptionNotifyRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.QueryMpanStatusResponse
     */
    @WebMethod
    @WebResult(name = "queryMpanStatusResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public QueryMpanStatusResponse queryMpanStatus(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "queryMpanStatusRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        QueryMpanStatusRequest parameters);

    /**
     * 
     * @param transNoDestination
     * @param transType
     * @param interfaceVersion
     * @param source
     * @param parameters
     * @param transNoSource
     * @param transTimeSource
     * @param destination
     * @param transTimeDestination
     * @return
     *     returns com.TransactionNotifyResponse
     */
    @WebMethod
    @WebResult(name = "transactionNotifyResponse", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
    public TransactionNotifyResponse transactionNotify(
        @WebParam(name = "interfaceVersion", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "interfaceVersion")
        Holder<String> interfaceVersion,
        @WebParam(name = "transTimeSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeSource")
        Holder<String> transTimeSource,
        @WebParam(name = "transTimeDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transTimeDestination")
        Holder<String> transTimeDestination,
        @WebParam(name = "transNoSource", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoSource")
        Holder<String> transNoSource,
        @WebParam(name = "transNoDestination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transNoDestination")
        Holder<String> transNoDestination,
        @WebParam(name = "transType", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "transType")
        Holder<String> transType,
        @WebParam(name = "source", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "source")
        Holder<String> source,
        @WebParam(name = "destination", targetNamespace = "http://ws.tsm.cup.com/", header = true, mode = WebParam.Mode.INOUT, partName = "destination")
        Holder<String> destination,
        @WebParam(name = "transactionNotifyRequest", targetNamespace = "http://ws.tsm.cup.com/", partName = "parameters")
        TransactionNotifyRequest parameters);

}
