
package com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TsmBankService", targetNamespace = "http://ws.tsm.cup.com/", wsdlLocation = "file:/C:/applepay/simulate/applePaySimulate/service/src/main/java/com/tsm-bank.wsdl")
public class TsmBankService
    extends Service
{

    private final static URL TSMBANKSERVICE_WSDL_LOCATION;
    private final static WebServiceException TSMBANKSERVICE_EXCEPTION;
    private final static QName TSMBANKSERVICE_QNAME = new QName("http://ws.tsm.cup.com/", "TsmBankService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/applepay/simulate/applePaySimulate/service/src/main/java/com/tsm-bank.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TSMBANKSERVICE_WSDL_LOCATION = url;
        TSMBANKSERVICE_EXCEPTION = e;
    }

    public TsmBankService() {
        super(__getWsdlLocation(), TSMBANKSERVICE_QNAME);
    }

    public TsmBankService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TSMBANKSERVICE_QNAME, features);
    }

    public TsmBankService(URL wsdlLocation) {
        super(wsdlLocation, TSMBANKSERVICE_QNAME);
    }

    public TsmBankService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TSMBANKSERVICE_QNAME, features);
    }

    public TsmBankService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TsmBankService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AmBankPortType
     */
    @WebEndpoint(name = "TsmBankPortType")
    public AmBankPortType getTsmBankPortType() {
        return super.getPort(new QName("http://ws.tsm.cup.com/", "TsmBankPortType"), AmBankPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AmBankPortType
     */
    @WebEndpoint(name = "TsmBankPortType")
    public AmBankPortType getTsmBankPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.tsm.cup.com/", "TsmBankPortType"), AmBankPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TSMBANKSERVICE_EXCEPTION!= null) {
            throw TSMBANKSERVICE_EXCEPTION;
        }
        return TSMBANKSERVICE_WSDL_LOCATION;
    }

}
